name: FartherViewDistance
version: ${project.version}
main: xuan.cat.fartherviewdistance.code.Index
api-version: 1.13
depend: [ProtocolLib]
authors: [xuancat0208]

commands:
  viewdistance:
    usage: op
